"""A49 -- Completeness Claim Binding.

Verifies:
1. Completeness claim binding in paper verify: when --completeness-check is
   used with --run-dir and the attestation has a stored completeness report,
   the verifier compares recomputed vs stored and sets
   completeness_trust_status accordingly.
2. Non-strict completeness warning: when completeness_strict=False and
   completeness fails in verified mode, result["completeness_warning"]=True.
3. Claim-only entries in verify-chain: entries without run_dir now have
   verified=False and claim_only=True (A49 fix from A46's verified=True).
"""

import hashlib
import io
import json
import os
import zipfile as zf_mod
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest
from typer.testing import CliRunner

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ai_workflow_hub.cli import app

runner = CliRunner()

# Default bundle_id used in test helpers
_BUNDLE_ID = "test-a49"


# ---------------------------------------------------------------------------
# Helpers (paper verify)
# ---------------------------------------------------------------------------

def _file_sha256(content: str) -> str:
    """Compute SHA-256 hex digest for string content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _make_bundle_manifest(files: dict[str, str], bundle_id: str = _BUNDLE_ID) -> dict:
    """Build a bundle_manifest.json dict from {path: content}.

    The bundle manifest ``files`` list only contains *user* files (the ones
    the audit command would have found in the run directory).  Metadata
    members (bundle_manifest.json, attestation.json, MANIFEST.json) are
    generated by the audit and are NOT in the files list.

    Computes per-file sha256 and the attestation content_hash so that
    the verify command's content_hash_valid check passes.
    """
    file_entries = []
    for path, content in files.items():
        file_entries.append({"path": path, "sha256": _file_sha256(content)})

    sorted_entries = sorted([(f["path"], f["sha256"]) for f in file_entries])
    content_hash = hashlib.sha256(
        json.dumps(sorted_entries, sort_keys=True).encode("utf-8")
    ).hexdigest()

    return {
        "bundle_id": bundle_id,
        "files": file_entries,
        "attestation": {"content_hash": content_hash},
    }


def _make_attestation(file_entries: list[dict], completeness=None) -> dict:
    """Build an attestation.json dict.

    artifact_hashes mirrors the non-generated file entries from the bundle
    manifest so that the verify command's attestation_consistency check passes.

    _AUDIT_GENERATED_MEMBERS = {bundle_manifest.json, attestation.json,
                                MANIFEST.json, artifact_chain.json}
    """
    generated = {"bundle_manifest.json", "attestation.json",
                 "MANIFEST.json", "artifact_chain.json"}
    artifact_hashes = [
        {"artifact": f["path"], "sha256": f["sha256"]}
        for f in file_entries
        if f["path"] not in generated
    ]
    att: dict = {"artifact_hashes": artifact_hashes}
    if completeness is not None:
        att["completeness"] = completeness
    return att


def _make_bundle_zip(
    tmp_path: Path,
    files: dict[str, str],
    completeness=None,
    zip_name: str = "bundle.zip",
    bundle_id: str = _BUNDLE_ID,
) -> str:
    """Create a minimal valid audit bundle ZIP and matching sidecar.

    The ZIP contains:
    - User files from *files*
    - bundle_manifest.json (files list = user files only)
    - attestation.json (artifact_hashes = user files only)
    - MANIFEST.json (file index for all ZIP members)

    A matching .sha256 sidecar is written alongside the ZIP.

    Returns the ZIP path as a string.
    """
    bm = _make_bundle_manifest(files, bundle_id=bundle_id)

    # All ZIP members: user files + metadata
    all_files = dict(files)
    all_files["bundle_manifest.json"] = json.dumps(bm, indent=2)
    all_files["attestation.json"] = json.dumps(
        _make_attestation(bm["files"], completeness), indent=2
    )

    # MANIFEST.json -- file index with sha256 for every member
    manifest_entries = []
    for path in sorted(all_files.keys()):
        manifest_entries.append({
            "path": path,
            "sha256": _file_sha256(all_files[path]),
        })
    # Self-entry for MANIFEST.json (hash must be "" so verify skips it)
    manifest_entries.append({"path": "MANIFEST.json", "sha256": ""})
    manifest_json = json.dumps({"files": manifest_entries}, indent=2)
    all_files["MANIFEST.json"] = manifest_json

    # Write the ZIP
    zip_path = tmp_path / zip_name
    with zf_mod.ZipFile(zip_path, "w") as z:
        for path, content in all_files.items():
            z.writestr(path, content)

    # Write sidecar so sidecar_hash_match passes
    actual_hash = hashlib.sha256(zip_path.read_bytes()).hexdigest()
    sidecar_path = Path(str(zip_path) + ".sha256")
    sidecar_path.write_text(f"{actual_hash}  {zip_path.name}\n", encoding="utf-8")

    return str(zip_path)


def _make_run_dir(
    tmp_path: Path,
    files: dict[str, str],
    dir_name: str = "run",
) -> str:
    """Create a mock run directory with the given files.

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")
    return str(rd)


def _make_policy(tmp_path: Path, policy_dict: dict, name: str = "policy.json") -> str:
    """Write a policy dict to a JSON file and return the path as string."""
    p = tmp_path / name
    p.write_text(json.dumps(policy_dict), encoding="utf-8")
    return str(p)


def _valid_policy(**overrides) -> dict:
    """Return a valid audit policy dict with optional overrides."""
    base = {
        "schema_version": "1.0",
        "signature_policy": "optional",
        "chain_verification_mode": "chain_only",
        "allowed_key_ids": [],
        "required_artifacts": [],
        "strict_chain": False,
        "strict_timestamps": True,
        "description": "test-policy-a49",
    }
    base.update(overrides)
    return base


# ---------------------------------------------------------------------------
# Helpers (verify-chain)
# ---------------------------------------------------------------------------

_RT_PATH = "ai_workflow_hub.cli._paper_runtime"
_PAPER_RUNS = "ai_workflow_hub.cli._paper_runs_root"


def _fake_runtime():
    return {
        "sanitize": lambda rid: rid,
        "create": MagicMock(), "execute": MagicMock(),
        "status": MagicMock(), "redact": lambda s: s,
    }


def _make_anchor_log(tmp_path: Path, n: int = 2, name: str = "chain.log") -> str:
    """Create a minimal valid anchor log JSONL file with n entries.

    Returns the log file path as a string.
    """
    log_path = tmp_path / name
    lines = []
    for i in range(n):
        entry = {
            "timestamp": f"2026-06-13T00:0{i}:00Z",
            "bundle_id": f"b{i}",
            "run_id": f"r{i}",
            "zip_sha256": f"{i}" * 64,
            "bundle_hash": f"h{i}",
            "signed": False,
        }
        if i > 0:
            prev_line = lines[-1]
            entry["prev_hash"] = hashlib.sha256(prev_line.encode("utf-8")).hexdigest()
        else:
            entry["prev_hash"] = ""
        lines.append(json.dumps(entry, ensure_ascii=False))
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(log_path)


def _invoke_verify_chain(log_path, extra_args=None):
    """Invoke paper verify-chain with patched consoles for clean JSON capture."""
    from rich.console import Console

    rt = _fake_runtime()
    _runner = CliRunner()
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    _console = Console(file=stdout_buf, force_terminal=False, width=4096)
    _err_console = Console(file=stderr_buf, force_terminal=False)

    args = ["paper", "verify-chain", "--log", str(log_path), "--json"]
    if extra_args:
        args.extend(extra_args)

    with patch(_RT_PATH, return_value=rt), \
         patch("ai_workflow_hub.cli.init_env"), \
         patch("ai_workflow_hub.cli.console", _console), \
         patch("ai_workflow_hub.cli.err_console", _err_console):
        result = _runner.invoke(app, args, catch_exceptions=False)

    return result, stdout_buf.getvalue(), stderr_buf.getvalue()


def _get_json_from_stdout(stdout: str) -> dict:
    """Extract JSON object from stdout that may contain progress lines."""
    lines = stdout.strip().split("\n")
    json_start = -1
    for i, line in enumerate(lines):
        if line.strip().startswith("{"):
            json_start = i
            break
    if json_start < 0:
        raise ValueError("No JSON found in stdout")
    return json.loads("\n".join(lines[json_start:]))


# ============================================================
# TestA49ClaimBinding
# ============================================================

class TestA49ClaimBinding:
    """Completeness claim binding: stored vs recomputed comparison."""

    def test_verified_matched(self, tmp_path):
        """Stored completeness matches recomputed -> trust_status is 'verified_matched'."""
        files = {"data.txt": "claim binding data"}
        # Stored completeness says complete=True, missing_count=0
        stored = {"complete": True, "missing_count": 0}
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)

        # Run directory matches bundle exactly -> recomputed complete=True, missing_count=0
        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_trust_status"] == "verified_matched"

    def test_verified_drift(self, tmp_path):
        """Stored completeness differs from recomputed -> trust_status is 'verified_drift'."""
        files = {"data.txt": "drift data"}
        # Stored completeness says complete=True, missing_count=0
        stored = {"complete": True, "missing_count": 0}
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)

        # Run directory has an extra orphan file -> recomputed complete=False, missing_count=1
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data not in bundle"
        rd = _make_run_dir(tmp_path, run_files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_trust_status"] == "verified_drift"

    def test_verified_no_claim(self, tmp_path):
        """No stored completeness in attestation -> trust_status is 'verified_no_claim'."""
        files = {"data.txt": "no claim data"}
        # No stored completeness in attestation
        zip_path = _make_bundle_zip(tmp_path, files, completeness=None)

        # Run directory matches bundle exactly
        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_trust_status"] == "verified_no_claim"


# ============================================================
# TestA49TrustStatusValues
# ============================================================

class TestA49TrustStatusValues:
    """All completeness_trust_status values across modes."""

    def test_claim_only_unverified(self, tmp_path):
        """Claim-only mode with stored completeness -> 'claim_only_unverified'."""
        stored = {"complete": True, "missing_count": 0}
        zip_path = _make_bundle_zip(
            tmp_path, {"data.txt": "claim data"},
            completeness=stored,
        )
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_trust_status"] == "claim_only_unverified"

    def test_claim_only_no_claim(self, tmp_path):
        """Claim-only mode without stored completeness -> 'claim_only_no_claim'."""
        zip_path = _make_bundle_zip(
            tmp_path, {"data.txt": "no stored claim"},
            completeness=None,
        )
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_trust_status"] == "claim_only_no_claim"

    def test_no_completeness_check(self, tmp_path):
        """Without --completeness-check, trust_status is not present or 'no_completeness'."""
        zip_path = _make_bundle_zip(tmp_path, {"data.txt": "basic data"})
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
        ])

        data = json.loads(result.stdout, strict=False)
        # Without --completeness-check, the A49 block is never entered,
        # so completeness_trust_status should not be in the result.
        assert "completeness_trust_status" not in data


# ============================================================
# TestA49NonStrictWarning
# ============================================================

class TestA49NonStrictWarning:
    """Non-strict completeness warning flag."""

    def test_non_strict_warning_flag(self, tmp_path):
        """completeness_strict=False and missing files -> completeness_warning=True."""
        files = {"data.txt": "base data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir -> completeness fails
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data"
        rd = _make_run_dir(tmp_path, run_files)

        # Policy with completeness_strict=False (non-strict)
        policy = _valid_policy(completeness_strict=False)
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_warning"] is True

    def test_strict_no_warning_flag(self, tmp_path):
        """completeness_strict=True and missing files -> no warning (it blocks instead)."""
        files = {"data.txt": "base data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir -> completeness fails
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data"
        rd = _make_run_dir(tmp_path, run_files)

        # Policy with completeness_strict=True (strict)
        policy = _valid_policy(completeness_strict=True)
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        # In strict mode, there is no warning flag -- it blocks instead
        assert "completeness_warning" not in data


# ============================================================
# TestA49VerifyChainClaimFix
# ============================================================

class TestA49VerifyChainClaimFix:
    """Verify-chain claim-only entries have verified=False, claim_only=True."""

    def test_claim_only_entries_not_verified(self, tmp_path):
        """verify-chain claim-only entries have verified=False and claim_only=True."""
        log_path = _make_anchor_log(tmp_path, n=2)

        result, stdout, _ = _invoke_verify_chain(log_path, [
            "--completeness-check",
        ])

        data = _get_json_from_stdout(stdout)
        rev = data.get("completeness_reverification", [])
        assert len(rev) >= 1
        for entry in rev:
            # A49 fix: claim-only entries must have verified=False
            assert entry["verified"] is False
            # A49 fix: claim-only entries must have claim_only=True
            assert entry["claim_only"] is True

    def test_chain_completeness_verdict_claim_only(self, tmp_path):
        """verify-chain completeness_verdict is 'claim_only' without run_dir."""
        log_path = _make_anchor_log(tmp_path, n=2)

        result, stdout, _ = _invoke_verify_chain(log_path, [
            "--completeness-check",
        ])

        data = _get_json_from_stdout(stdout)
        assert data["completeness_verdict"] == "claim_only"
