"""A48 -- Consistent Completeness Verdict Semantics.

Verifies:
1. Deferred verdict computation: final verdict and trust_summary are
   computed AFTER the completeness check block, not before.
2. completeness_verdict field on paper verify: "verified",
   "verified_failed", "claim_only", "error", "unknown".
3. trust_summary completeness suffix: _complete, _incomplete, _claim_only.
4. verify-chain completeness_verdict: "verified", "verified_partial",
   "verified_failed", "claim_only".
5. verify-chain verification_mode suffix: _complete, _partial,
   _incomplete, _claim_only.
6. Backward compatibility: no suffix without --completeness-check.
"""

import hashlib
import io
import json
import os
import zipfile as zf_mod
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest
from typer.testing import CliRunner

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ai_workflow_hub.cli import app

runner = CliRunner()

# Default bundle_id used in test helpers
_BUNDLE_ID = "test-a48"


# ---------------------------------------------------------------------------
# Helpers (paper verify)
# ---------------------------------------------------------------------------

def _file_sha256(content: str) -> str:
    """Compute SHA-256 hex digest for string content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _make_bundle_manifest(files: dict[str, str], bundle_id: str = _BUNDLE_ID) -> dict:
    """Build a bundle_manifest.json dict from {path: content}.

    The bundle manifest ``files`` list only contains *user* files (the ones
    the audit command would have found in the run directory).  Metadata
    members (bundle_manifest.json, attestation.json, MANIFEST.json) are
    generated by the audit and are NOT in the files list.

    Computes per-file sha256 and the attestation content_hash so that
    the verify command's content_hash_valid check passes.
    """
    file_entries = []
    for path, content in files.items():
        file_entries.append({"path": path, "sha256": _file_sha256(content)})

    sorted_entries = sorted([(f["path"], f["sha256"]) for f in file_entries])
    content_hash = hashlib.sha256(
        json.dumps(sorted_entries, sort_keys=True).encode("utf-8")
    ).hexdigest()

    return {
        "bundle_id": bundle_id,
        "files": file_entries,
        "attestation": {"content_hash": content_hash},
    }


def _make_attestation(file_entries: list[dict], completeness=None) -> dict:
    """Build an attestation.json dict.

    artifact_hashes mirrors the non-generated file entries from the bundle
    manifest so that the verify command's attestation_consistency check passes.

    _AUDIT_GENERATED_MEMBERS = {bundle_manifest.json, attestation.json,
                                MANIFEST.json, artifact_chain.json}
    """
    generated = {"bundle_manifest.json", "attestation.json",
                 "MANIFEST.json", "artifact_chain.json"}
    artifact_hashes = [
        {"artifact": f["path"], "sha256": f["sha256"]}
        for f in file_entries
        if f["path"] not in generated
    ]
    att: dict = {"artifact_hashes": artifact_hashes}
    if completeness is not None:
        att["completeness"] = completeness
    return att


def _make_bundle_zip(
    tmp_path: Path,
    files: dict[str, str],
    completeness=None,
    zip_name: str = "bundle.zip",
    bundle_id: str = _BUNDLE_ID,
) -> str:
    """Create a minimal valid audit bundle ZIP and matching sidecar.

    The ZIP contains:
    - User files from *files*
    - bundle_manifest.json (files list = user files only)
    - attestation.json (artifact_hashes = user files only)
    - MANIFEST.json (file index for all ZIP members)

    A matching .sha256 sidecar is written alongside the ZIP.

    Returns the ZIP path as a string.
    """
    bm = _make_bundle_manifest(files, bundle_id=bundle_id)

    # All ZIP members: user files + metadata
    all_files = dict(files)
    all_files["bundle_manifest.json"] = json.dumps(bm, indent=2)
    all_files["attestation.json"] = json.dumps(
        _make_attestation(bm["files"], completeness), indent=2
    )

    # MANIFEST.json -- file index with sha256 for every member
    manifest_entries = []
    for path in sorted(all_files.keys()):
        manifest_entries.append({
            "path": path,
            "sha256": _file_sha256(all_files[path]),
        })
    # Self-entry for MANIFEST.json (hash must be "" so verify skips it)
    manifest_entries.append({"path": "MANIFEST.json", "sha256": ""})
    manifest_json = json.dumps({"files": manifest_entries}, indent=2)
    all_files["MANIFEST.json"] = manifest_json

    # Write the ZIP
    zip_path = tmp_path / zip_name
    with zf_mod.ZipFile(zip_path, "w") as z:
        for path, content in all_files.items():
            z.writestr(path, content)

    # Write sidecar so sidecar_hash_match passes
    actual_hash = hashlib.sha256(zip_path.read_bytes()).hexdigest()
    sidecar_path = Path(str(zip_path) + ".sha256")
    sidecar_path.write_text(f"{actual_hash}  {zip_path.name}\n", encoding="utf-8")

    return str(zip_path)


def _make_run_dir(
    tmp_path: Path,
    files: dict[str, str],
    dir_name: str = "run",
) -> str:
    """Create a mock run directory with the given files.

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")
    return str(rd)


def _make_run_dir_with_persisted(
    tmp_path: Path,
    user_files: dict[str, str],
    zip_path: str,
    bundle_id: str = _BUNDLE_ID,
    extra_files: dict[str, str] | None = None,
    dir_name: str = "run",
) -> str:
    """Create a run directory with user files and a persisted bundle manifest.

    The persisted manifest is written at
    ``<run_dir>/bundle_manifest_<bundle_id>.json`` with the correct
    ``zip_sha256`` so that check 10 (persisted_manifest_zip_sha256) passes.

    *extra_files* are additional files placed in the run directory (useful
    for simulating orphan files or policy-ignored artifacts).

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)

    # Write user files
    for name, content in user_files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")

    # Write extra files
    if extra_files:
        for name, content in extra_files.items():
            fpath = rd / name
            fpath.parent.mkdir(parents=True, exist_ok=True)
            fpath.write_text(content, encoding="utf-8")

    # Write persisted bundle manifest
    zip_hash = hashlib.sha256(Path(zip_path).read_bytes()).hexdigest()
    persisted = {
        "bundle_id": bundle_id,
        "zip_sha256": zip_hash,
    }
    persisted_path = rd / f"bundle_manifest_{bundle_id}.json"
    persisted_path.write_text(json.dumps(persisted), encoding="utf-8")

    return str(rd)


def _make_policy(tmp_path: Path, policy_dict: dict, name: str = "policy.json") -> str:
    """Write a policy dict to a JSON file and return the path as string."""
    p = tmp_path / name
    p.write_text(json.dumps(policy_dict), encoding="utf-8")
    return str(p)


def _valid_policy(**overrides) -> dict:
    """Return a valid audit policy dict with optional overrides."""
    base = {
        "schema_version": "1.0",
        "signature_policy": "optional",
        "chain_verification_mode": "chain_only",
        "allowed_key_ids": [],
        "required_artifacts": [],
        "strict_chain": False,
        "strict_timestamps": True,
        "description": "test-policy-a48",
    }
    base.update(overrides)
    return base


# ---------------------------------------------------------------------------
# Helpers (verify-chain)
# ---------------------------------------------------------------------------

_RT_PATH = "ai_workflow_hub.cli._paper_runtime"
_PAPER_RUNS = "ai_workflow_hub.cli._paper_runs_root"


def _fake_runtime():
    return {
        "sanitize": lambda rid: rid,
        "create": MagicMock(), "execute": MagicMock(),
        "status": MagicMock(), "redact": lambda s: s,
    }


def _make_anchor_log(tmp_path: Path, n: int = 2, name: str = "chain.log") -> str:
    """Create a minimal valid anchor log JSONL file with n entries.

    Returns the log file path as a string.
    """
    log_path = tmp_path / name
    lines = []
    for i in range(n):
        entry = {
            "timestamp": f"2026-06-13T00:0{i}:00Z",
            "bundle_id": f"b{i}",
            "run_id": f"r{i}",
            "zip_sha256": f"{i}" * 64,
            "bundle_hash": f"h{i}",
            "signed": False,
        }
        if i > 0:
            prev_line = lines[-1]
            entry["prev_hash"] = hashlib.sha256(prev_line.encode("utf-8")).hexdigest()
        else:
            entry["prev_hash"] = ""
        lines.append(json.dumps(entry, ensure_ascii=False))
    log_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(log_path)


def _invoke_verify_chain(log_path, extra_args=None):
    """Invoke paper verify-chain with patched consoles for clean JSON capture."""
    from rich.console import Console

    rt = _fake_runtime()
    _runner = CliRunner()
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    _console = Console(file=stdout_buf, force_terminal=False, width=4096)
    _err_console = Console(file=stderr_buf, force_terminal=False)

    args = ["paper", "verify-chain", "--log", str(log_path), "--json"]
    if extra_args:
        args.extend(extra_args)

    with patch(_RT_PATH, return_value=rt), \
         patch("ai_workflow_hub.cli.init_env"), \
         patch("ai_workflow_hub.cli.console", _console), \
         patch("ai_workflow_hub.cli.err_console", _err_console):
        result = _runner.invoke(app, args, catch_exceptions=False)

    return result, stdout_buf.getvalue(), stderr_buf.getvalue()


def _get_json_from_stdout(stdout: str) -> dict:
    """Extract JSON object from stdout that may contain progress lines."""
    lines = stdout.strip().split("\n")
    json_start = -1
    for i, line in enumerate(lines):
        if line.strip().startswith("{"):
            json_start = i
            break
    if json_start < 0:
        raise ValueError("No JSON found in stdout")
    return json.loads("\n".join(lines[json_start:]))


# ============================================================
# TestA48DeferredVerdict
# ============================================================

class TestA48DeferredVerdict:
    """Verdict and trust_summary are computed AFTER completeness check."""

    def test_verdict_reflects_completeness_failure(self, tmp_path):
        """When completeness fails (extra file in run_dir), verdict is 'failed'."""
        files = {"data.txt": "base data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir not in bundle manifest
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data not in bundle"
        rd = _make_run_dir(tmp_path, run_files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        # The completeness check found missing files -> check failed
        assert data["failed"] > 0
        # A48: Verdict is computed AFTER completeness block, so it reflects
        # the completeness failure
        assert data["verdict"] == "failed"

    def test_verdict_reflects_completeness_success(self, tmp_path):
        """When completeness passes (all files match), verdict is 'passed'."""
        files = {"data.txt": "complete data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Use persisted run_dir so check 10 (persisted_manifest) passes.
        # The persisted manifest file is an extra file in the run_dir that
        # would normally be flagged as missing from the bundle.  We use a
        # policy with ignored_artifacts to exclude it from the completeness
        # scan so that only user files are compared.
        rd = _make_run_dir_with_persisted(tmp_path, files, zip_path)

        policy = _valid_policy(ignored_artifacts=["bundle_manifest_*.json"])
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["verdict"] == "passed"
        assert data["completeness_verdict"] == "verified"
        assert data["completeness"]["complete"] is True

    def test_trust_summary_includes_completeness_suffix(self, tmp_path):
        """When completeness passes, trust_summary ends with '_complete'."""
        files = {"data.txt": "suffix check data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["trust_summary"].endswith("_complete")


# ============================================================
# TestA48CompletenessVerdictField
# ============================================================

class TestA48CompletenessVerdictField:
    """completeness_verdict field on paper verify result."""

    def test_verified_mode(self, tmp_path):
        """completeness_verdict is 'verified' when all files match."""
        files = {"data.txt": "verified data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_verdict"] == "verified"

    def test_verified_failed_mode(self, tmp_path):
        """completeness_verdict is 'verified_failed' when files are missing."""
        files = {"data.txt": "base data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra file in run_dir not in bundle -> completeness fails
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data"
        rd = _make_run_dir(tmp_path, run_files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_verdict"] == "verified_failed"

    def test_claim_only_mode(self, tmp_path):
        """completeness_verdict is 'claim_only' when no --run-dir."""
        zip_path = _make_bundle_zip(tmp_path, {"data.txt": "claim data"})

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_verdict"] == "claim_only"


# ============================================================
# TestA48VerifyChainVerdict
# ============================================================

class TestA48VerifyChainVerdict:
    """completeness_verdict and verification_mode suffix on verify-chain."""

    def test_chain_completeness_verdict_field(self, tmp_path):
        """verify-chain --completeness-check without --run-dir: claim_only."""
        log_path = _make_anchor_log(tmp_path, n=2)

        result, stdout, _ = _invoke_verify_chain(log_path, [
            "--completeness-check",
        ])

        data = _get_json_from_stdout(stdout)
        assert "completeness_verdict" in data
        assert data["completeness_verdict"] == "claim_only"

    def test_chain_verification_mode_suffix(self, tmp_path):
        """With --completeness-check and no --run-dir, verification_mode
        contains '_claim_only'."""
        log_path = _make_anchor_log(tmp_path, n=2)

        result, stdout, _ = _invoke_verify_chain(log_path, [
            "--completeness-check",
        ])

        data = _get_json_from_stdout(stdout)
        assert "_claim_only" in data["verification_mode"]


# ============================================================
# TestA48BackwardCompat
# ============================================================

class TestA48BackwardCompat:
    """Backward compatibility: no completeness suffix without the flag."""

    def test_no_completeness_no_suffix(self, tmp_path):
        """Without --completeness-check, trust_summary has no completeness suffix."""
        zip_path = _make_bundle_zip(tmp_path, {"data.txt": "basic data"})

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
        ])

        data = json.loads(result.stdout, strict=False)
        ts = data["trust_summary"]
        assert "_complete" not in ts
        assert "_incomplete" not in ts
        assert "_claim_only" not in ts

    def test_existing_checks_unaffected(self, tmp_path):
        """Standard verify checks still work identically."""
        files = {"data.txt": "well-formed bundle"}
        zip_path = _make_bundle_zip(tmp_path, files)

        rd = _make_run_dir_with_persisted(tmp_path, files, zip_path)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
        ])

        assert result.exit_code == 0, (
            f"Expected exit_code 0 but got {result.exit_code}. "
            f"stderr: {result.stderr}"
        )
        data = json.loads(result.stdout, strict=False)
        assert data["verdict"] == "passed"
        assert data["failed"] == 0
