"""A50 -- Policy-Adjusted Completeness Results.

Verifies:
1. Raw vs policy completeness pass: raw_completeness_pass captures the
   unadjusted verification result, while policy_completeness_pass reflects
   the policy-adjusted outcome (strict block vs non-strict warn).
2. Drift severity: completeness_drift_severity ("none", "low", "high")
   and completeness_drift_dims count the dimensions of difference between
   stored and recomputed completeness claims.
3. Non-strict warning: completeness_policy_action="warn" does NOT force
   verdict failure; completeness_warning=True is set.
4. Backward compatibility: completeness_verdict and
   completeness_trust_status values remain consistent with A47-A49.
"""

import hashlib
import io
import json
import os
import zipfile as zf_mod
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest
from typer.testing import CliRunner

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ai_workflow_hub.cli import app

runner = CliRunner()

# Default bundle_id used in test helpers
_BUNDLE_ID = "test-a50"


# ---------------------------------------------------------------------------
# Helpers (paper verify)
# ---------------------------------------------------------------------------

def _file_sha256(content: str) -> str:
    """Compute SHA-256 hex digest for string content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _make_bundle_manifest(files: dict[str, str], bundle_id: str = _BUNDLE_ID) -> dict:
    """Build a bundle_manifest.json dict from {path: content}.

    The bundle manifest ``files`` list only contains *user* files (the ones
    the audit command would have found in the run directory).  Metadata
    members (bundle_manifest.json, attestation.json, MANIFEST.json) are
    generated by the audit and are NOT in the files list.

    Computes per-file sha256 and the attestation content_hash so that
    the verify command's content_hash_valid check passes.
    """
    file_entries = []
    for path, content in files.items():
        file_entries.append({"path": path, "sha256": _file_sha256(content)})

    sorted_entries = sorted([(f["path"], f["sha256"]) for f in file_entries])
    content_hash = hashlib.sha256(
        json.dumps(sorted_entries, sort_keys=True).encode("utf-8")
    ).hexdigest()

    return {
        "bundle_id": bundle_id,
        "files": file_entries,
        "attestation": {"content_hash": content_hash},
    }


def _make_attestation(file_entries: list[dict], completeness=None) -> dict:
    """Build an attestation.json dict.

    artifact_hashes mirrors the non-generated file entries from the bundle
    manifest so that the verify command's attestation_consistency check passes.

    _AUDIT_GENERATED_MEMBERS = {bundle_manifest.json, attestation.json,
                                MANIFEST.json, artifact_chain.json}
    """
    generated = {"bundle_manifest.json", "attestation.json",
                 "MANIFEST.json", "artifact_chain.json"}
    artifact_hashes = [
        {"artifact": f["path"], "sha256": f["sha256"]}
        for f in file_entries
        if f["path"] not in generated
    ]
    att: dict = {"artifact_hashes": artifact_hashes}
    if completeness is not None:
        att["completeness"] = completeness
    return att


def _make_bundle_zip(
    tmp_path: Path,
    files: dict[str, str],
    completeness=None,
    zip_name: str = "bundle.zip",
    bundle_id: str = _BUNDLE_ID,
) -> str:
    """Create a minimal valid audit bundle ZIP and matching sidecar.

    The ZIP contains:
    - User files from *files*
    - bundle_manifest.json (files list = user files only)
    - attestation.json (artifact_hashes = user files only)
    - MANIFEST.json (file index for all ZIP members)

    A matching .sha256 sidecar is written alongside the ZIP.

    Returns the ZIP path as a string.
    """
    bm = _make_bundle_manifest(files, bundle_id=bundle_id)

    # All ZIP members: user files + metadata
    all_files = dict(files)
    all_files["bundle_manifest.json"] = json.dumps(bm, indent=2)
    all_files["attestation.json"] = json.dumps(
        _make_attestation(bm["files"], completeness), indent=2
    )

    # MANIFEST.json -- file index with sha256 for every member
    manifest_entries = []
    for path in sorted(all_files.keys()):
        manifest_entries.append({
            "path": path,
            "sha256": _file_sha256(all_files[path]),
        })
    # Self-entry for MANIFEST.json (hash must be "" so verify skips it)
    manifest_entries.append({"path": "MANIFEST.json", "sha256": ""})
    manifest_json = json.dumps({"files": manifest_entries}, indent=2)
    all_files["MANIFEST.json"] = manifest_json

    # Write the ZIP
    zip_path = tmp_path / zip_name
    with zf_mod.ZipFile(zip_path, "w") as z:
        for path, content in all_files.items():
            z.writestr(path, content)

    # Write sidecar so sidecar_hash_match passes
    actual_hash = hashlib.sha256(zip_path.read_bytes()).hexdigest()
    sidecar_path = Path(str(zip_path) + ".sha256")
    sidecar_path.write_text(f"{actual_hash}  {zip_path.name}\n", encoding="utf-8")

    return str(zip_path)


def _make_run_dir(
    tmp_path: Path,
    files: dict[str, str],
    dir_name: str = "run",
) -> str:
    """Create a mock run directory with the given files.

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")
    return str(rd)


def _make_run_dir_with_persisted(
    tmp_path: Path,
    user_files: dict[str, str],
    zip_path: str,
    bundle_id: str = _BUNDLE_ID,
    extra_files: dict[str, str] | None = None,
    dir_name: str = "run",
) -> str:
    """Create a run directory with user files and a persisted bundle manifest.

    The persisted manifest is written at
    ``<run_dir>/bundle_manifest_<bundle_id>.json`` with the correct
    ``zip_sha256`` so that check 10 (persisted_manifest_zip_sha256) passes.

    *extra_files* are additional files placed in the run directory (useful
    for simulating orphan files or policy-ignored artifacts).

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)

    # Write user files
    for name, content in user_files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")

    # Write extra files
    if extra_files:
        for name, content in extra_files.items():
            fpath = rd / name
            fpath.parent.mkdir(parents=True, exist_ok=True)
            fpath.write_text(content, encoding="utf-8")

    # Write persisted bundle manifest
    zip_hash = hashlib.sha256(Path(zip_path).read_bytes()).hexdigest()
    persisted = {
        "bundle_id": bundle_id,
        "zip_sha256": zip_hash,
    }
    persisted_path = rd / f"bundle_manifest_{bundle_id}.json"
    persisted_path.write_text(json.dumps(persisted), encoding="utf-8")

    return str(rd)


def _make_policy(tmp_path: Path, policy_dict: dict, name: str = "policy.json") -> str:
    """Write a policy dict to a JSON file and return the path as string."""
    p = tmp_path / name
    p.write_text(json.dumps(policy_dict), encoding="utf-8")
    return str(p)


def _valid_policy(**overrides) -> dict:
    """Return a valid audit policy dict with optional overrides."""
    base = {
        "schema_version": "1.0",
        "signature_policy": "optional",
        "chain_verification_mode": "chain_only",
        "allowed_key_ids": [],
        "required_artifacts": [],
        "strict_chain": False,
        "strict_timestamps": True,
        "description": "test-policy-a50",
    }
    base.update(overrides)
    return base


# ============================================================
# TestA50RawVsPolicy
# ============================================================

class TestA50RawVsPolicy:
    """Raw vs policy completeness pass: raw captures unadjusted result,
    policy reflects strict/non-strict adjustment."""

    def test_raw_pass_policy_pass(self, tmp_path):
        """Completeness verified+complete -> raw=True, policy=True, action='pass'."""
        files = {"data.txt": "complete a50 data"}
        # Stored completeness matches recomputed: complete=True, missing_count=0
        stored = {
            "complete": True,
            "missing_count": 0,
            "total_run_files": 1,
            "total_ignored": 0,
        }
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)

        # Run directory matches bundle exactly
        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["raw_completeness_pass"] is True
        assert data["policy_completeness_pass"] is True
        assert data["completeness_policy_action"] == "pass"

    def test_raw_fail_strict_block(self, tmp_path):
        """Completeness fails+strict -> raw=False, policy=False, action='block'."""
        files = {"data.txt": "strict block data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir -> completeness fails
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data not in bundle"
        rd = _make_run_dir(tmp_path, run_files)

        policy = _valid_policy(completeness_strict=True)
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["raw_completeness_pass"] is False
        assert data["policy_completeness_pass"] is False
        assert data["completeness_policy_action"] == "block"

    def test_raw_fail_nonstrict_warn(self, tmp_path):
        """Completeness fails+non-strict -> raw=False, policy=True, action='warn'."""
        files = {"data.txt": "nonstrict warn data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir -> completeness fails
        # Use persisted run_dir so check 10 passes; ignore persisted manifest
        rd = _make_run_dir_with_persisted(
            tmp_path, files, zip_path,
            extra_files={"extra-orphan.dat": "orphan data not in bundle"},
        )

        policy = _valid_policy(
            completeness_strict=False,
            ignored_artifacts=["bundle_manifest_*.json"],
        )
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["raw_completeness_pass"] is False
        assert data["policy_completeness_pass"] is True
        assert data["completeness_policy_action"] == "warn"


# ============================================================
# TestA50DriftSeverity
# ============================================================

class TestA50DriftSeverity:
    """Drift severity and dimension count: stored vs recomputed comparison
    across 5 dimensions (complete, missing_count, total_run_files,
    policy_sha256, total_ignored)."""

    def test_drift_none_matched(self, tmp_path):
        """Stored matches recomputed -> drift_severity='none', drift_dims=0."""
        files = {"data.txt": "matched drift data"}
        # Stored completeness exactly matches recomputed values
        stored = {
            "complete": True,
            "missing_count": 0,
            "total_run_files": 1,
            "total_ignored": 0,
        }
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)

        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_drift_severity"] == "none"
        assert data["completeness_drift_dims"] == 0
        assert data["completeness_trust_status"] == "verified_matched"

    def test_drift_low_one_dim(self, tmp_path):
        """Stored differs in 1 dimension -> drift_severity='low'."""
        files = {"data.txt": "low drift data"}
        # Stored total_run_files differs (99 vs recomputed 1)
        # Other dimensions match or use sentinel -1 (skip)
        stored = {
            "complete": True,
            "missing_count": 0,
            "total_run_files": 99,
        }
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)

        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_drift_severity"] == "low"
        assert data["completeness_drift_dims"] == 1
        assert data["completeness_trust_status"] == "verified_drift"

    def test_drift_high_multi_dim(self, tmp_path):
        """Stored differs in 2+ dimensions -> drift_severity='high'."""
        files = {"data.txt": "high drift data"}
        # Stored total_run_files and total_ignored both differ
        stored = {
            "complete": True,
            "missing_count": 0,
            "total_run_files": 99,
            "total_ignored": 99,
        }
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)

        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_drift_severity"] == "high"
        assert data["completeness_drift_dims"] >= 2
        assert data["completeness_trust_status"] == "verified_drift"


# ============================================================
# TestA50NonStrictWarning
# ============================================================

class TestA50NonStrictWarning:
    """Non-strict completeness warning: policy_action='warn' does NOT
    force verdict failure; completeness_warning=True is set."""

    def test_warning_does_not_fail_verdict(self, tmp_path):
        """Non-strict completeness failure does NOT make verdict 'failed'."""
        files = {"data.txt": "verdict check data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Use persisted run_dir so check 10 passes; ignore persisted manifest
        # Extra orphan file in run_dir -> completeness fails
        rd = _make_run_dir_with_persisted(
            tmp_path, files, zip_path,
            extra_files={"extra-orphan.dat": "orphan data not in bundle"},
        )

        policy = _valid_policy(
            completeness_strict=False,
            ignored_artifacts=["bundle_manifest_*.json"],
        )
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        # A50 key assertion: verdict is NOT "failed" despite completeness failure
        assert data["verdict"] != "failed"
        # Policy-adjusted outcome is pass-with-warning
        assert data["policy_completeness_pass"] is True
        assert data["completeness_policy_action"] == "warn"

    def test_warning_sets_completeness_warning_flag(self, tmp_path):
        """completeness_warning=True is set on non-strict completeness failure."""
        files = {"data.txt": "warning flag data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir -> completeness fails
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data not in bundle"
        rd = _make_run_dir(tmp_path, run_files)

        policy = _valid_policy(completeness_strict=False)
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_warning"] is True
        # Raw result captures the unadjusted failure
        assert data["raw_completeness_pass"] is False


# ============================================================
# TestA50BackwardCompat
# ============================================================

class TestA50BackwardCompat:
    """Backward compatibility: completeness_verdict and
    completeness_trust_status values remain consistent with A47-A49."""

    def test_existing_completeness_verdict_values(self, tmp_path):
        """completeness_verdict values still work as before (A48 semantics)."""
        # Verified+complete -> "verified"
        files = {"data.txt": "verdict compat data"}
        zip_path = _make_bundle_zip(tmp_path, files)
        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_verdict"] == "verified"

        # Verified+failed -> "verified_failed"
        zip_path2 = _make_bundle_zip(
            tmp_path, files, zip_name="bundle2.zip",
        )
        run_files = dict(files)
        run_files["orphan.dat"] = "orphan"
        rd2 = _make_run_dir(tmp_path, run_files, dir_name="run2")

        result2 = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path2,
            "--run-dir", rd2,
            "--json",
            "--completeness-check",
        ])

        data2 = json.loads(result2.stdout, strict=False)
        assert data2["completeness_verdict"] == "verified_failed"

        # Claim-only -> "claim_only"
        zip_path3 = _make_bundle_zip(
            tmp_path, files, zip_name="bundle3.zip",
        )
        result3 = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path3,
            "--json",
            "--completeness-check",
        ])

        data3 = json.loads(result3.stdout, strict=False)
        assert data3["completeness_verdict"] == "claim_only"

    def test_existing_trust_status_values(self, tmp_path):
        """completeness_trust_status values still work as before (A49 semantics)."""
        # verified_matched
        files = {"data.txt": "trust compat data"}
        stored = {"complete": True, "missing_count": 0}
        zip_path = _make_bundle_zip(tmp_path, files, completeness=stored)
        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert data["completeness_trust_status"] == "verified_matched"

        # verified_no_claim (no stored completeness)
        zip_path2 = _make_bundle_zip(
            tmp_path, files, completeness=None, zip_name="bundle2.zip",
        )
        rd2 = _make_run_dir(tmp_path, files, dir_name="run2")

        result2 = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path2,
            "--run-dir", rd2,
            "--json",
            "--completeness-check",
        ])

        data2 = json.loads(result2.stdout, strict=False)
        assert data2["completeness_trust_status"] == "verified_no_claim"

        # claim_only_unverified (claim-only with stored completeness)
        zip_path3 = _make_bundle_zip(
            tmp_path, files, completeness=stored, zip_name="bundle3.zip",
        )
        result3 = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path3,
            "--json",
            "--completeness-check",
        ])

        data3 = json.loads(result3.stdout, strict=False)
        assert data3["completeness_trust_status"] == "claim_only_unverified"
