"""A47 -- Verifier-Side Completeness Re-verification.

Verifies:
1. --completeness-check option exists on paper verify command
2. With --run-dir: re-computes completeness by comparing run directory files
   against the bundle manifest (bm_data["files"])
3. Without --run-dir: falls back to claim-only mode, checking stored
   completeness data in the attestation
4. Policy-controlled classification: ignored_artifacts (glob) and
   generated_artifacts (exact match)
5. Hash-redacted missing file reporting (path_hash + basename)
6. completeness report in result JSON
7. Backward compatibility: verify works without --completeness-check
"""

import hashlib
import json
import os
import zipfile as zf_mod
from pathlib import Path

import pytest
from typer.testing import CliRunner

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ai_workflow_hub.cli import app

runner = CliRunner()

# Default bundle_id used in test helpers
_BUNDLE_ID = "test-a47"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _file_sha256(content: str) -> str:
    """Compute SHA-256 hex digest for string content."""
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def _make_bundle_manifest(files: dict[str, str], bundle_id: str = _BUNDLE_ID) -> dict:
    """Build a bundle_manifest.json dict from {path: content}.

    The bundle manifest ``files`` list only contains *user* files (the ones
    the audit command would have found in the run directory).  Metadata
    members (bundle_manifest.json, attestation.json, MANIFEST.json) are
    generated by the audit and are NOT in the files list.

    Computes per-file sha256 and the attestation content_hash so that
    the verify command's content_hash_valid check passes.
    """
    file_entries = []
    for path, content in files.items():
        file_entries.append({"path": path, "sha256": _file_sha256(content)})

    sorted_entries = sorted([(f["path"], f["sha256"]) for f in file_entries])
    content_hash = hashlib.sha256(
        json.dumps(sorted_entries, sort_keys=True).encode("utf-8")
    ).hexdigest()

    return {
        "bundle_id": bundle_id,
        "files": file_entries,
        "attestation": {"content_hash": content_hash},
    }


def _make_attestation(file_entries: list[dict], completeness=None) -> dict:
    """Build an attestation.json dict.

    artifact_hashes mirrors the non-generated file entries from the bundle
    manifest so that the verify command's attestation_consistency check passes.

    _AUDIT_GENERATED_MEMBERS = {bundle_manifest.json, attestation.json,
                                MANIFEST.json, artifact_chain.json}
    """
    generated = {"bundle_manifest.json", "attestation.json",
                 "MANIFEST.json", "artifact_chain.json"}
    artifact_hashes = [
        {"artifact": f["path"], "sha256": f["sha256"]}
        for f in file_entries
        if f["path"] not in generated
    ]
    att: dict = {"artifact_hashes": artifact_hashes}
    if completeness is not None:
        att["completeness"] = completeness
    return att


def _make_bundle_zip(
    tmp_path: Path,
    files: dict[str, str],
    completeness=None,
    zip_name: str = "bundle.zip",
    bundle_id: str = _BUNDLE_ID,
) -> str:
    """Create a minimal valid audit bundle ZIP and matching sidecar.

    The ZIP contains:
    - User files from *files*
    - bundle_manifest.json (files list = user files only)
    - attestation.json (artifact_hashes = user files only)
    - MANIFEST.json (file index for all ZIP members)

    A matching .sha256 sidecar is written alongside the ZIP.

    Returns the ZIP path as a string.
    """
    bm = _make_bundle_manifest(files, bundle_id=bundle_id)

    # All ZIP members: user files + metadata
    all_files = dict(files)
    all_files["bundle_manifest.json"] = json.dumps(bm, indent=2)
    all_files["attestation.json"] = json.dumps(
        _make_attestation(bm["files"], completeness), indent=2
    )

    # MANIFEST.json -- file index with sha256 for every member
    manifest_entries = []
    for path in sorted(all_files.keys()):
        manifest_entries.append({
            "path": path,
            "sha256": _file_sha256(all_files[path]),
        })
    # Self-entry for MANIFEST.json (hash must be "" so verify skips it)
    manifest_entries.append({"path": "MANIFEST.json", "sha256": ""})
    manifest_json = json.dumps({"files": manifest_entries}, indent=2)
    all_files["MANIFEST.json"] = manifest_json

    # Write the ZIP
    zip_path = tmp_path / zip_name
    with zf_mod.ZipFile(zip_path, "w") as z:
        for path, content in all_files.items():
            z.writestr(path, content)

    # Write sidecar so sidecar_hash_match passes
    actual_hash = hashlib.sha256(zip_path.read_bytes()).hexdigest()
    sidecar_path = Path(str(zip_path) + ".sha256")
    sidecar_path.write_text(f"{actual_hash}  {zip_path.name}\n", encoding="utf-8")

    return str(zip_path)


def _make_run_dir(
    tmp_path: Path,
    files: dict[str, str],
    dir_name: str = "run",
) -> str:
    """Create a mock run directory with the given files.

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")
    return str(rd)


def _make_run_dir_with_persisted(
    tmp_path: Path,
    user_files: dict[str, str],
    zip_path: str,
    bundle_id: str = _BUNDLE_ID,
    extra_files: dict[str, str] | None = None,
    dir_name: str = "run",
) -> str:
    """Create a run directory with user files and a persisted bundle manifest.

    The persisted manifest is written at
    ``<run_dir>/bundle_manifest_<bundle_id>.json`` with the correct
    ``zip_sha256`` so that check 10 (persisted_manifest_zip_sha256) passes.

    *extra_files* are additional files placed in the run directory (useful
    for simulating orphan files or policy-ignored artifacts).

    Returns the run directory path as a string.
    """
    rd = tmp_path / dir_name
    rd.mkdir(parents=True, exist_ok=True)

    # Write user files
    for name, content in user_files.items():
        fpath = rd / name
        fpath.parent.mkdir(parents=True, exist_ok=True)
        fpath.write_text(content, encoding="utf-8")

    # Write extra files
    if extra_files:
        for name, content in extra_files.items():
            fpath = rd / name
            fpath.parent.mkdir(parents=True, exist_ok=True)
            fpath.write_text(content, encoding="utf-8")

    # Write persisted bundle manifest
    zip_hash = hashlib.sha256(Path(zip_path).read_bytes()).hexdigest()
    persisted = {
        "bundle_id": bundle_id,
        "zip_sha256": zip_hash,
    }
    persisted_path = rd / f"bundle_manifest_{bundle_id}.json"
    persisted_path.write_text(json.dumps(persisted), encoding="utf-8")

    return str(rd)


def _make_policy(tmp_path: Path, policy_dict: dict, name: str = "policy.json") -> str:
    """Write a policy dict to a JSON file and return the path as string."""
    p = tmp_path / name
    p.write_text(json.dumps(policy_dict), encoding="utf-8")
    return str(p)


def _valid_policy(**overrides) -> dict:
    """Return a valid audit policy dict with optional overrides."""
    base = {
        "schema_version": "1.0",
        "signature_policy": "optional",
        "chain_verification_mode": "chain_only",
        "allowed_key_ids": [],
        "required_artifacts": [],
        "strict_chain": False,
        "strict_timestamps": True,
        "description": "test-policy-a47",
    }
    base.update(overrides)
    return base


# ============================================================
# TestA47VerifyOption
# ============================================================

class TestA47VerifyOption:
    """--completeness-check option on paper verify command."""

    def test_verify_has_completeness_check_option(self):
        """--completeness-check is a recognized option on paper verify."""
        result = runner.invoke(app, ["paper", "verify", "--help"])
        assert result.exit_code == 0
        combined = (result.stdout or "") + (result.stderr or "")
        # Typer may truncate long option names in help output; check for
        # the distinctive prefix that cannot appear from any other option.
        assert "--completeness-ch" in combined or "--completeness-check" in combined

    def test_verify_completeness_in_json(self, tmp_path):
        """paper verify --json --completeness-check produces completeness in JSON."""
        zip_path = _make_bundle_zip(tmp_path, {"data.txt": "hello a47"})
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])
        # Parse JSON from stdout (progress messages go to stderr)
        data = json.loads(result.stdout, strict=False)
        assert "completeness" in data


# ============================================================
# TestA47ClaimOnly
# ============================================================

class TestA47ClaimOnly:
    """Claim-only mode: --completeness-check without --run-dir."""

    def test_claim_only_without_run_dir(self, tmp_path):
        """Without --run-dir, completeness mode is claim_only."""
        stored = {"complete": True, "missing_count": 0}
        zip_path = _make_bundle_zip(
            tmp_path, {"data.txt": "claim data"},
            completeness=stored,
        )
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])
        data = json.loads(result.stdout, strict=False)
        assert "completeness" in data
        assert data["completeness"]["mode"] == "claim_only"

    def test_claim_only_with_stored_completeness(self, tmp_path):
        """Stored completeness data in attestation is found and reported."""
        stored = {"complete": True, "missing_count": 0, "total_run_files": 5}
        zip_path = _make_bundle_zip(
            tmp_path, {"data.txt": "stored data"},
            completeness=stored,
        )
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])
        data = json.loads(result.stdout, strict=False)
        comp = data["completeness"]
        assert comp["mode"] == "claim_only"
        assert "stored_completeness" in comp
        assert comp["stored_completeness"]["complete"] is True

    def test_claim_only_without_stored_completeness(self, tmp_path):
        """No stored completeness in attestation: claim check fails."""
        zip_path = _make_bundle_zip(
            tmp_path, {"data.txt": "no completeness here"},
            completeness=None,
        )
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
            "--completeness-check",
        ])
        data = json.loads(result.stdout, strict=False)
        comp = data["completeness"]
        assert comp["mode"] == "claim_only"
        assert comp["verified"] is False


# ============================================================
# TestA47FullReverification
# ============================================================

class TestA47FullReverification:
    """Full re-verification: --completeness-check --run-dir."""

    def test_verified_complete(self, tmp_path):
        """All run_dir files match bundle manifest: complete=True, mode=verified."""
        files = {"data.txt": "complete data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Run directory contains exactly the user files listed in the
        # bundle manifest.  We use _make_run_dir (not the persisted
        # variant) because the persisted manifest file would be an extra
        # file in the run_dir not listed in the bundle manifest.
        rd = _make_run_dir(tmp_path, files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        assert "completeness" in data
        comp = data["completeness"]
        assert comp["mode"] == "verified"
        assert comp["complete"] is True
        assert comp["missing_count"] == 0

    def test_verified_missing_files(self, tmp_path):
        """Files in run_dir not in bundle manifest are detected as missing."""
        files = {"data.txt": "base data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # Extra orphan file in run_dir that is NOT in the bundle manifest
        run_files = dict(files)
        run_files["extra-orphan.dat"] = "orphan data not in bundle"
        rd = _make_run_dir(tmp_path, run_files)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        comp = data["completeness"]
        assert comp["mode"] == "verified"
        assert comp["complete"] is False
        assert comp["missing_count"] > 0
        assert len(comp["missing_from_bundle"]) > 0
        # Each missing entry is a dict with path_hash and basename
        for entry in comp["missing_from_bundle"]:
            assert isinstance(entry, dict)
            assert "path_hash" in entry
            assert "basename" in entry

    def test_verified_with_policy_ignored(self, tmp_path):
        """Files matching ignored_artifacts patterns are excluded from missing."""
        files = {"data.txt": "base data"}
        zip_path = _make_bundle_zip(tmp_path, files)

        # debug.log in run_dir would normally be reported as missing,
        # but ignored_artifacts=["*.log"] excludes it.
        run_files = dict(files)
        run_files["debug.log"] = "debug trace output"
        rd = _make_run_dir(tmp_path, run_files)

        policy = _valid_policy(ignored_artifacts=["*.log"])
        policy_path = _make_policy(tmp_path, policy)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--policy", policy_path,
            "--json",
            "--completeness-check",
        ])

        data = json.loads(result.stdout, strict=False)
        comp = data["completeness"]
        assert comp["mode"] == "verified"
        # .log file excluded by policy -> no missing files
        assert comp["complete"] is True
        assert comp["missing_count"] == 0
        assert comp["total_ignored"] >= 1


# ============================================================
# TestA47BackwardCompat
# ============================================================

class TestA47BackwardCompat:
    """Backward compatibility: verify works without --completeness-check."""

    def test_verify_without_completeness_check(self, tmp_path):
        """Without --completeness-check, no completeness key in result."""
        zip_path = _make_bundle_zip(tmp_path, {"data.txt": "basic data"})
        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--json",
        ])
        data = json.loads(result.stdout, strict=False)
        assert "completeness" not in data

    def test_existing_verify_checks_still_pass(self, tmp_path):
        """Standard checks still pass on a well-formed ZIP with run_dir."""
        files = {"data.txt": "well-formed bundle"}
        zip_path = _make_bundle_zip(tmp_path, files)

        rd = _make_run_dir_with_persisted(tmp_path, files, zip_path)

        result = runner.invoke(app, [
            "paper", "verify",
            "--zip", zip_path,
            "--run-dir", rd,
            "--json",
        ])

        assert result.exit_code == 0, (
            f"Expected exit_code 0 but got {result.exit_code}. "
            f"stderr: {result.stderr}"
        )
        data = json.loads(result.stdout, strict=False)
        assert data["verdict"] == "passed"
        assert data["failed"] == 0
